### ISSUE TITLE
Use fake-fetch in JSFiddle

### ISSUE THREAD

**Issue by maryam-saeidi** [msn0/fake-fetch#1]
Is it possible that I use this library in JSFiddle?
I wrote some sample code in this link, and I am not sure how to use this library in it:
http://jsfiddle.net/maryam_saeidi/yredb06m/7/

**Comment by msn0** [comment]
Hi, you should require fake-fetch somehow. I'm not sure if there's any way to do it in JSFiddle. Maybe you can try RequireBin if that's an option http://requirebin.com/

**Comment by maryam-saeidi** [comment]
Thanks, I found some other solutions.
https://stackoverflow.com/questions/45946284/mock-http-fetch-in-sinon
