### ISSUE TITLE
Methods don't work as expected when fetch is provided a Request object

### ISSUE THREAD

**Issue by CoreyDH** [msn0/fake-fetch#5]
If you use the **Request** (https://developer.mozilla.org/en-US/docs/Web/API/Request) object as the only argument for your fetch implementation, methods such as _getUrl_ , _getMethod_, etc. stop working correctly.

**fake-fetch** is always expecting two arguments from fetch, a URL and options.  Can you add support for a single Request object argument?

You can add a conditional to check arguments
`if (arg instanceof Request)`

**Comment by msn0** [comment]
Thank you @CoreyDH. I'll take a look at it.

**Comment by msn0** [comment]
@CoreyDH please use  📦 fake-fetch@2.2.0
